services:
  - type: web
    name: bargain
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    branch: master
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false
      - key: DB_NAME
        value: bargain
